FROM mongo
RUN mkdir -p /data
ADD data/*.json /data/
RUN mongod & \
	mongoimport --db test --collection customers /data/customers.json && \
	mongoimport --db test --collection entries /data/entries.json && \
	pkill mongod
CMD ["mongod"]