FROM mongo
RUN mkdir -p /data
ADD data/*.json /data/
# at build time add data
RUN mongod & \
	mongoimport --db test --collection customers /data/customers.json && \
	mongoimport --db test --collection entries /data/entries.json 
	
VOLUME /data/db /data/configdb
EXPOSE 27017

ENTRYPOINT ["/entrypoint.sh"]
CMD ["mongod"]